services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
      - "9999:9999"
    volumes:
      - ./logs:/var/log/server-shepherd
    environment:
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8000
    restart: unless-stopped

  log-agent:
    build:
      context: .
      dockerfile: Dockerfile.backend
    command: ["python", "log_agent.py", "/var/log/server-shepherd/sample.log", "backend", "9999"]
    volumes:
      - ./logs:/var/log/server-shepherd
    depends_on:
      - backend
    restart: unless-stopped

  log-generator:
    build:
      context: .
      dockerfile: Dockerfile.backend
    command: ["python", "sample_log_generator.py", "/var/log/server-shepherd/sample.log", "0.5"]
    volumes:
      - ./logs:/var/log/server-shepherd
    restart: unless-stopped
